name: Auto Tag and Release (MAJOR.MINOR)

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    env:
      REPO: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag and compute new one
        id: get_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+$' | head -n1)

          if [ -z "$latest_tag" ]; then
            new_tag="v0.1"
            previous_tag=""
          else
            major=$(echo "$latest_tag" | cut -d. -f1 | sed 's/v//')
            minor=$(echo "$latest_tag" | cut -d. -f2)
            if [ "$minor" -lt 9 ]; then
              new_tag="v${major}.$((minor + 1))"
            else
              new_tag="v$((major + 1)).0"
            fi
            previous_tag="$latest_tag"
          fi

          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
          echo "PREVIOUS_TAG=$previous_tag" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Generate changelog
        run: |
          if [ -z "$PREVIOUS_TAG" ]; then
            log=$(git log --pretty=format:"- %s" -n 20)
          else
            log=$(git log --pretty=format:"- %s" "$PREVIOUS_TAG"..HEAD)
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$log" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          body: |
            🚀 **Release ${{ env.NEW_TAG }}**

            ### Changelog
            ${{ env.CHANGELOG }}

            🔗 [Full Changelog](https://github.com/${{ env.REPO }}/compare/${{ env.PREVIOUS_TAG || 'main' }}...${{ env.NEW_TAG }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
