name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag version
        id: get_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            🚀 Release ${{ env.VERSION }} is published.

            - Docker images tagged with this version.
            - Check changelog and docs for details.

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
