name: rl-fin-flow-client ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: rl-fin-flow-frontend application
        run: npm run build

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker build and push
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ghcr.io/rumenterziev/rl-fin-flow-frontend:v1 .
          docker push ghcr.io/rumenterziev/rl-fin-flow-frontend:v1
