name: Build and Push Docker Images to GHCR - Frontend

on:
  workflow_run:
    workflows: ["Auto Tag and Release (MAJOR.MINOR)"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build rl-fin-flow-frontend application
        run: npm run build

      - name: Get tag version
        run: echo "VERSION=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Docker login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Images
        run: |
          TAG="${{ github.event.workflow_run.head_commit.message }}" # fallback
          if [[ -n "${{ github.event.workflow_run.head_commit.id }}" ]]; then
            TAG=$(git describe --tags --exact-match ${{ github.event.workflow_run.head_commit.id }} 2>/dev/null || echo "${{ github.event.workflow_run.head_branch }}")
          fi

          # Use the new tag from the release workflow:
          VERSION="${{ github.event.workflow_run.head_branch }}"

          VERSION_IMAGE="ghcr.io/rumenterziev/dlrfinflow-frontend:${VERSION}"
          LATEST_IMAGE="ghcr.io/rumenterziev/dlrfinflow-frontend:latest"

          echo "Building Docker image: $VERSION_IMAGE"
          docker build -t "$VERSION_IMAGE" -t "$LATEST_IMAGE" .

          echo "Pushing $VERSION_IMAGE"
          docker push "$VERSION_IMAGE"

          echo "Pushing $LATEST_IMAGE"
          docker push "$LATEST_IMAGE"
